server:
  port: 8051
  
spring:
  application:
    name: cloud-client
  cloud:
    stream:
      bindings: 
        myInput:
          group: groupA    # 相同组自会有一个实例会收到消息
          
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
      registryFetch-IntervalSeconds: 30
      
feign:
  hystrix:
    enabled: true
    
hystrix:
  threadpool: 
    coreSize: 10    # 线程数  默认10个
  command: 
    default:           # default 对全局生效,可配置为服务名称 或 接口名#方法名
      fallback:
        enabled: true  # 是否关闭回退方法
      circuitreaker:
        requestVolumeThreshold: 3   # 当在配置时间窗口内达到此数量的失败后，进行短路。默认20个
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000     # 超时时间 默认 1000ms
            
logging:
  level:
    com:
      itcase:
        cloud:
          feign:
            PersonClient: debug   # 设置feign 客户端日志级别, feign的日志都是debug级别
        
jsch:
  port: 23
  user: zhouhaibo
  
management:
  security:
     enabled: false
