server:
  port: 8085
management:
  security:
    enabled: false      # 不启用安全机制
encrypt:
  #key: myKey      #使用对称算法使用此配置(AES)
  keyStore:        #非对称算法时使用的配置(RSA)
    location: classpath:/myTest.keystore  # keystroe位置
    password: '{cipher}3a20c8aafca495967e12e14527490ed7eb4ff25911582a777e1bbb949fb43f59'                    # 密钥库的
    alias: testKey                        # 密钥对的别名
    secret: 797e316ce5c1dc9ce02d6eca929ee48c577efd2e379d79171d454a9b816818cd                        # 密钥口令
